config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  get '/tasks/:id/complete', to: 'tasks#complete', as: 'complete_task'
  get '/tasks/:id/uncomplete', to: 'tasks#uncomplete', as: 'uncomplete_task'
  resources :tasks do
    collection do
      delete :batch_delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :priority, numericality: { greater_than: 0 }
  validate  :due_date_cannot_be_in_past
  def due_date_cannot_be_in_past
    if dueDate.present? && dueDate < Date.today
      errors.add(:dueDate, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :rememberable,:recoverable,
  devise :database_authenticatable, :registerable,
         :validatable,:confirmable
  def full_name
    return firstName+secondName;
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:firstName, :secondName,])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @completed_sorted=params[:completed_sorted]
    @not_completed_sorted=params[:not_completed_sorted]
    @tasks_not_completed=current_user.tasks.where(["done = ? ", false])
    @tasks_completed=current_user.tasks.where(["done = ? ", true])
    if(@completed_sorted)
      @tasks_completed=current_user.tasks.where(["done = ? ", true]).order(:title)
    end
    if(@not_completed_sorted)
      @tasks_not_completed=current_user.tasks.where(["done = ? ", false]).order(:title)
    end
  end
  def new
    @task=Task.new
  end
  def batch_delete
    Task.where(id: params[:collection_ids]).destroy_all
    redirect_to tasks_path
  end
  def complete
    @task = Task.find(params[:id])
    @task.done=true
    @task.save
    redirect_to tasks_path
  end
  def uncomplete
    @task= Task.find(params[:id])
    @task.done=false
    @task.save
    redirect_to tasks_path
  end
  def show
    @task = Task.find(params[:id])
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    if(@task.update(task_params))
      redirect_to tasks_path
    else
      render 'edit'
    end
  end
  def destroy
    @task = Task.find(params[:id])
    @task.delete
    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.json { head :no_content }
      format.js
    end
  end
  def create
    @task=current_user.tasks.create(task_params)
    @task.done=false
    if(@task.save)
      redirect_to tasks_path
    else
      render 'new'
    end
  end
  private def task_params
    params.require(:task).permit(:title,:description,:priority, :dueDate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex flex-column p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <nav class="navbar navbar-light bg-light justify-content-between">
        <a class="navbar-brand">Task Manager</a>
        <span class="navbar-text ">
          <span class="mr-2">
            <%= link_to "Main page", tasks_path %>
          </span>
            <span class="mr-2">
          <%if signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <%else %>
            <%= link_to "Login", new_user_session_path %>
          <%end %>
          </span>
          <%= link_to "Sing up", new_user_registration_path %>
        </span>


      </nav>
    </header>
    <p class="notice text-warning font-weight-bold"><%= notice %></p>
    <p class="alert text-danger font-weight-bold"><%= alert  %></p>
    <div class="container">

    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/destroy.js.erb
$('.delete').bind('ajax:success', function() {
    $(this).closest('dl').fadeOut();
});

app/views/tasks/edit.html.erb
  <h2>Edit task</h2>
  <%= form_for :task, url: task_path(@task), method: :patch do |f| %>
    <% if @task.errors.any? %>
      <% @task.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <%end %>
    <% end %>
    <%= f.label :Title %><br />
    <%= f.text_field(:title, :class => 'form-control w-50') %>
    <%= f.label :Description %><br />
    <%= f.text_area(:description, :class => 'form-control w-50') %>
    <%= f.label :Priority %><br />
    <%= f.number_field(:priority, :class => 'form-control w-50') %>
    <%= f.label :Due_Date %><br />
    <%= f.date_field(:dueDate, :class => 'form-control w-50') %>
    <%= f.submit("Save", :class => 'btn btn-warning mt-2') %>
  <% end %>

app/views/tasks/index.html.erb
<script>
    $(document).ready(function(){
        $('#check_all').on("click", function() {
            let checkboxes = $('input[type="checkbox"]');
            checkboxes.prop("checked",true);
        });
    });
    $(document).ready(function(){
        $('#uncheck_all').on("click", function() {
            let checkboxes = $('input[type="checkbox"]');
            checkboxes.prop("checked",false);
        });
    });
    $(document).ready(function() {
        $(".hover").hover(
            function () {
                $('[id=' + "task_" + this.id + ']').removeClass("d-none")
            },
            function () {
                let id = this.id;
                setTimeout(function () {
                    $('[id=' + "task_" + id + ']').addClass("d-none")
                }, 1500);
            }
        );
    });

</script>
<%= form_for :tasks, url: "/tasks/batch_delete", method: :delete  do |f| %>
<h3 class="mt-2"><%= link_to "All tasks to do:" ,tasks_path(:not_completed_sorted=>true), :class=>"text-dark"%></h3>
  <p class="font-weight-light s">press to sort tasks</p>
  <div class="not_completed_tasks">
  <%if not @tasks_not_completed.nil? %>
      <% @tasks_not_completed.each do |task1| %>
      <dl class="row">
        <dt class="col-sm-7 mb-2 mt-1">
          <h4 >
            <input class =" mr-2" type="checkbox"  name="collection_ids[]" value="<%= task1.id %>"/>
          <%= link_to task1.title, task_path(task1),:class => 'text-dark hover mr-3',id: task1.id.to_s%>
            <%=link_to "Edit task", edit_task_path(task1),:class => 'btn btn-warning mr-3  d-none',id: "task_"+task1.id.to_s%>
            <%= link_to "Delete task", task_path(task1),method: :delete,remote: true,:class => 'btn btn-danger delete d-none',id: "task_"+task1.id.to_s%> </h4></dt>
        <dd class="col-sm-3 mb-2 mt-1"><%= link_to "Complete task", complete_task_path(task1),:class => 'complete btn btn-warning mb-4' %></dd>
      </dl>
      <% end %>
  <% end %>
  </div>
  <h3 class="mt-2"><%= link_to "All completed tasks:" ,tasks_path(:completed_sorted=>true), :class=>"text-dark" %></h3>
  <p class="font-weight-light s">press to sort tasks</p>
  <div class="completed_tasks">
  <%if not @tasks_not_completed.nil? %>
    <% @tasks_completed.each do |task2| %>
      <dl class="row">
        <dt class="col-sm-7 mb-2 mt-1">
          <h4 >
            <input class =" mr-2" type="checkbox"  name="collection_ids[]" value="<%= task2.id %>"/>
            <%= link_to task2.title, task_path(task2),:class => 'text-dark hover mr-3',id: task2.id.to_s%>
            <%=link_to "Edit task", edit_task_path(task2),:class => 'btn btn-warning mr-3 d-none',id: "task_"+task2.id.to_s%>
            <%= link_to "Delete task", task_path(task2),method: :delete,remote: true,:class => 'btn btn-danger d-none delete',id: "task_"+task2.id.to_s%>
          </h4>
        </dt>
        <dd class="col-sm-3  mb-2 mt-1"><%= link_to "Make active", uncomplete_task_path(task2),:class => 'uncomplete btn btn-warning mb-4' %></dd>
      </dl>
    <% end %>
    <br>
  <% end %>
  </div>
  <%= link_to "Add task", new_task_path(),:class => 'btn btn-info mt-2 w-25' %>
  <%= f.submit("Batch delete", :class => 'btn btn-danger mt-2 w-25')%>
<%end %>
<button class="btn btn-success w-25 mt-3" id="check_all">Check all</button>
<button class="btn btn-success w-25 mt-3" id="uncheck_all">Uncheck all</button>

app/views/tasks/new.html.erb
<h3>Create new task</h3>
<%= form_for :task, url: tasks_path do |f| %>
  <% if @task.errors.any? %>
    <% @task.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end %>
  <% end %>
  <%= f.label :Title ,:class => 'form-check-label'%><br />
  <%= f.text_field(:title, :class => 'form-control w-50') %>
  <%= f.label :Description ,:class => 'form-check-label'%><br />
  <%= f.text_area(:description, :class => 'form-control w-50') %>
  <%= f.label :Priority ,:class => 'form-check-label'%><br />
  <%= f.number_field(:priority, :class => 'form-control w-50') %>
  <%= f.label :Due_Date ,:class => 'form-check-label '%><br />
  <%= f.date_field(:dueDate, :class => 'form-control w-50') %>
  <%= f.submit("Create", :class => 'btn btn-warning mt-2') %>
<% end %>

app/views/tasks/show.html.erb
<h3 ><%= @task.title %></h3>
<dl class="row">
  <dt class="col-sm-3">Description:</dt>
  <dd class="col-sm-9"><%= @task.description %></dd>
  <dt class="col-sm-3">Priority:</dt>
  <dd class="col-sm-9"><%= @task.priority %></dd>
  <dt class="col-sm-3">Due date:</dt>
  <dd class="col-sm-9"><%= @task.dueDate %></dd>
  <dt class="col-sm-3">Completed:</dt>
  <%if @task.done? %>
    <dd class="col-sm-9"><input type="checkbox" checked disabled></dd>
    <%else%>
  <dd class="col-sm-9"><input type="checkbox" disabled></dd>
  <%end %>
</dl>
  <%= link_to "Edit task", edit_task_path(@task),:class => 'btn btn-warning' %>